name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "LICENSE"

  release:
    types: [published]

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      dev: ${{steps.retrieve_sha.outputs.sha}}
      release: ${{steps.parse_semver.outputs.fullversion}}
    steps:
      - name: Check-out repo
        uses: actions/checkout@v3

      - name: Retrieve short form of latest commit hash (SHA)
        id: retrieve_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Parse SemVer (release)
        id: parse_semver
        if: startsWith(github.ref, 'refs/tags/')
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{github.ref}}
          version_extractor_regex: '\/v(.*)$'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Check-out repo
        uses: actions/checkout@v3

      - name: Set-up AMXX compiler
        uses: wopox1337/setup-amxxpawn@v1
        with:
          version: '1.10.x'
      
      - name: Include short SHA in plugin versions
        working-directory: cstrike/addons/amxmodx/scripting
        run: |
          for sma in *.sma; do
            sed -i 's/,.VERSION/, VERSION+"-${{needs.version.outputs.dev}}"/g' $sma
          done

      - name: Compile plugins
        working-directory: cstrike/addons/amxmodx/scripting
        run: |
          mkdir ../plugins
          for sma in *.sma; do
            amxxpc $sma -i"include" -o"../plugins/$(echo $sma | sed -e 's/.sma/.amxx/')"
          done

      - name: Move `cstrike/` to `publish/`
        run: |
          mkdir publish
          mv cstrike/ publish/

      - name: Upload artifact (`cstrike/`)
        uses: actions/upload-artifact@v3
        with:
          name: anti-rc-${{needs.version.outputs.dev}}-dev
          path: publish/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [version, build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact (`cstrike/`)
        uses: actions/download-artifact@v3
        with:
          name: anti-rc-${{needs.version.outputs.dev}}-dev

      - name: Archive `cstrike` directory
        id: archive
        run: 7z a -t7z anti-rc-${{needs.version.outputs.release}}.7z cstrike

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.archive.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: |
            *.7z
